services:
  spark-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-jupyter
    ports:
      - "8889:8888"  # Jupyter Notebook
      - "4040:4040"  # Spark UI
      - "7077:7077"  # Spark Master
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      # Configurações para acessar o MinIO
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/.jupyter
    networks:
      - mybridge

networks:
  mybridge:
    external: true